<!-- ## intro to scikit learn lib -->

In [280]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

heart_disease = pd.read_csv("../zero-to-mastery-ml-master/zero-to-mastery-ml-master/data/heart-disease.csv")

heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [281]:
# except Target , all columns are feature var columns

#create X (features matrix)
X= heart_disease.drop("target",axis=1)
X

#create Y (labels)
y = heart_disease["target"]
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [282]:
#choose a right model and hyperparameters

from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=100)
#keeping default params
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [283]:
#fit model to training data
from sklearn.model_selection import train_test_split
X_train, X_test ,y_train , y_test = train_test_split(X,y,test_size=0.2) 
clf.fit(X_train , y_train)

#make a prediction 
y_preds = clf.predict(X_test)
y_preds

array([0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1])

In [284]:
y_test

20     1
263    0
75     1
225    0
187    0
      ..
78     1
72     1
185    0
165    0
281    0
Name: target, Length: 61, dtype: int64

In [285]:
# evaluate the model
clf.score(X_train,y_train)

1.0

In [286]:
clf.score(X_test,y_test)

0.8524590163934426

In [287]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.86      0.83      0.84        29
           1       0.85      0.88      0.86        32

    accuracy                           0.85        61
   macro avg       0.85      0.85      0.85        61
weighted avg       0.85      0.85      0.85        61

In [288]:
# confusion_matrix(y_test,y_preds)

In [289]:
accuracy_score(y_test,y_preds)

0.8524590163934426

In [290]:
#improve model
#try different amount of n_estimators
np.random.seed(42)

for i in range(10,100,10):
    print(f"trying models with {i} estimators")
    clf= RandomForestClassifier(n_estimators=i).fit(X_train,y_train)
    # clf.fit(X_train,y_train)
    print(f"model accuracy on test set : {clf.score(X_test,y_test)*100:.2f}%")

trying models with 10 estimators
model accuracy on test set : 77.05%
trying models with 20 estimators
model accuracy on test set : 80.33%
trying models with 30 estimators
model accuracy on test set : 77.05%
trying models with 40 estimators
model accuracy on test set : 80.33%
trying models with 50 estimators
model accuracy on test set : 81.97%
trying models with 60 estimators
model accuracy on test set : 77.05%
trying models with 70 estimators
model accuracy on test set : 81.97%
trying models with 80 estimators
model accuracy on test set : 80.33%
trying models with 90 estimators
model accuracy on test set : 78.69%

In [291]:
#save a model and load it
import pickle
pickle.dump(clf,open("randomForestmod1.pkl","wb"))

In [292]:
loaded_model = pickle.load(open("randomForestmod1.pkl","rb"))
loaded_model.score(X_test,y_test)

0.7868852459016393

In [293]:
import sklearn
sklearn.show_versions()

System:
    python: 3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]
executable: c:\Users\Sanjay B\anaconda3\python.exe
   machine: Windows-11-10.0.26100-SP0

Python dependencies:
      sklearn: 1.7.0
          pip: 24.2
   setuptools: 75.1.0
        numpy: 2.3.1
        scipy: 1.16.0
       Cython: None
       pandas: 2.3.1
   matplotlib: 3.10.3
       joblib: 1.4.2
threadpoolctl: 3.6.0

Built with OpenMP: True

threadpoolctl info:
       user_api: blas
   internal_api: openblas
    num_threads: 8
         prefix: libscipy_openblas
       filepath: C:\Users\Sanjay B\anaconda3\Lib\site-packages\numpy.libs\libscipy_openblas64_-13e2df515630b4a41f92893938845698.dll
        version: 0.3.29
threading_layer: pthreads
   architecture: SkylakeX

       user_api: openmp
   internal_api: openmp
    num_threads: 8
         prefix: vcomp
       filepath: C:\Users\Sanjay B\anaconda3\Lib\site-packages\sklearn\.libs\vcomp140.dll
        version: None

       user_api: blas
   internal_api: openblas
    num_threads: 8
         prefix: libscipy_openblas
       filepath: C:\Users\Sanjay B\anaconda3\Lib\site-packages\scipy.libs\libscipy_openblas-f07f5a5d207a3a47104dca54d6d0c86a.dll
        version: 0.3.28
threading_layer: pthreads
   architecture: SkylakeX

In [294]:
## getting data ready to be used with machine learning

'''
split the data into features and labels (X and y)
filling or imputing or disregarding missing values
conveting non-numeric values to numeric called feature encoding

'''

'\nsplit the data into features and labels (X and y)\nfilling or imputing or disregarding missing values\nconveting non-numeric values to numeric called feature encoding\n\n'

In [295]:
heart_disease.head()
X = heart_disease.drop("target",axis=1)
X
y = heart_disease["target"]
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [296]:
# split the data into training and test data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [297]:
carsales = pd.read_csv("../zero-to-mastery-ml-master/zero-to-mastery-ml-master/data/car-sales-extended.csv")
carsales.head()

X = carsales.drop("Price",axis=1)
y= carsales["Price"]
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [298]:
#Building machine learning models
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train,y_train)
model.score(X_test,y_test)

ValueError: could not convert string to float: 'Toyota'

In [ ]:
#converting non-numeric columns to numeric
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make","Colour","Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot',
                                  one_hot,
                                  categorical_features)],
                                  remainder="passthrough")

transformed_x = transformer.fit_transform(X)
df_transformed = pd.DataFrame(transformed_x)
df_transformed

      0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [ ]:
dummies = pd.get_dummies(carsales[['Make',"Colour","Doors"]])
dummies

,Doors,Make_BMW,Make_Honda,Make_Nissan,Make_Toyota,Colour_Black,Colour_Blue,Colour_Green,Colour_Red,Colour_White
0,4,False,True,False,False,False,False,False,False,True
1,5,True,False,False,False,False,True,False,False,False
2,4,False,True,False,False,False,False,False,False,True
3,4,False,False,False,True,False,False,False,False,True
4,3,False,False,True,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...
995,4,False,False,False,True,True,False,False,False,False
996,3,False,False,True,False,False,False,False,False,True
997,4,False,False,True,False,False,True,False,False,False
998,4,False,True,False,False,False,False,False,False,True
999,4,False,False,False,True,False,True,False,False,False

In [ ]:
from sklearn.ensemble import RandomForestRegressor
np.random.seed(42)

model = RandomForestRegressor()

X_train,X_test,y_train,y_test = train_test_split(transformed_x,y,test_size=0.2)
model.fit(X_train,y_train)
# transformed_x

RandomForestRegressor()

In [307]:
model.score(X_test,y_test)

0.0975453770499638

In [ ]:
# creating X and y
car_sales_missing = pd.read_csv("../zero-to-mastery-ml-master/zero-to-mastery-ml-master/data/car-sales-extended-missing-data.csv")

X = car_sales_missing.drop("Price",axis=1)
y = car_sales_missing["Price"]

In [ ]:

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

car_sales_missing = pd.read_csv("../zero-to-mastery-ml-master/zero-to-mastery-ml-master/data/car-sales-extended-missing-data.csv")

car_sales_missing.dropna(inplace=True)


X= car_sales_missing.drop("Price",axis=1)
y = car_sales_missing["Price"]

categorical_features = ["Make","Colour","Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot',
                                  one_hot,
                                  categorical_features)],
                                  remainder="passthrough")

transformed_x = transformer.fit_transform(car_sales_missing)
df_transformed = pd.DataFrame(transformed_x)
df_transformed
# car_sales_missing.shape

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,35431.0,15323.0
1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,192714.0,19943.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,84714.0,28343.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,154365.0,13434.0
4,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,181577.0,14043.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
768,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,163322.0,31666.0
769,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,35820.0,32042.0
770,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,66604.0,31570.0
771,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,215883.0,4001.0
772,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,248360.0,12732.0

In [ ]:
car_sales_missing = pd.read_csv("../zero-to-mastery-ml-master/zero-to-mastery-ml-master/data/car-sales-extended-missing-data.csv")
car_sales_missing.isna().sum()

car_sales_missing.dropna(subset=["Price"],inplace=True)
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [323]:
# split into X and y

car_sales_missing["Price"] = car_sales_missing["Price"].replace('[\$\,]',"",regex=True).astype("int")
car_sales_missing

X = car_sales_missing.drop("Price",axis=1)
y = car_sales_missing["Price"]

<>:3: SyntaxWarning: invalid escape sequence '\$'
<>:3: SyntaxWarning: invalid escape sequence '\$'
C:\Users\Sanjay B\AppData\Local\Temp\ipykernel_25116\1107737766.py:3: SyntaxWarning: invalid escape sequence '\$'
  car_sales_missing["Price"] = car_sales_missing["Price"].replace('[\$\,]',"",regex=True).astype("int")

In [324]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

#fill categorical with "missing" and numerical values with "mean"

cat_imputer = SimpleImputer(strategy="constant", fill_value="missing")
door_imputer = SimpleImputer(strategy="constant",fill_value=4)
num_imputer = SimpleImputer(strategy="mean")

#define columns

cat_features = ["Make","Colour"]
num_features = ["Odometer (KM)"]
door_features = ["Doors"]

#creating an imputer (something that fills the data)
imputer = ColumnTransformer([
    ("cat_imputer",cat_imputer,cat_features),
    ("num_imputer",num_imputer,num_features),
    ("door_imputer",door_imputer,door_features)
                             ])
filled_X = imputer.fit_transform(X)
filled_X

array([['Honda', 'White', 35431.0, 4.0],
       ['BMW', 'Blue', 192714.0, 5.0],
       ['Honda', 'White', 84714.0, 4.0],
       ...,
       ['Nissan', 'Blue', 66604.0, 4.0],
       ['Honda', 'White', 215883.0, 4.0],
       ['Toyota', 'Blue', 248360.0, 4.0]], shape=(950, 4), dtype=object)

In [325]:
car_sales_filled = pd.DataFrame(filled_X,columns=["Make","Colour","Doors","Odometer (KM)"])
car_sales_filled
car_sales_filled.isna().sum()

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [326]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make","Colour","Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot',
                                  one_hot,
                                  categorical_features)],
                                  remainder="passthrough")

transformed_x = transformer.fit_transform(car_sales_filled).toarray()
df_transformed = pd.DataFrame(transformed_x)
df_transformed

,0,1,2,3,4,5,6,7,8,9,...,903,904,905,906,907,908,909,910,911,912
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
1,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
946,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
947,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
948,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
949,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0

In [327]:
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(df_transformed,y,test_size=0.2)
model = RandomForestRegressor(n_estimators=100)
model.fit(X_train,y_train)
model.score(X_train,y_train)
model.score(X_test,y_test)

-0.044955128011236356